theme: minima
title: Qigang's homepage
description: |
  ZHANG Qigang | Daniel
  PolyU | 21102826D@connect.polyu.hk
baseurl: "" # the subpath of your site, e.g. /blog
header_pages:
  - index.md
  - research.md
  - internship.md
  - activities.md
