theme: Mediumish
title: Qigang's homepage
description: |
  ZHANG Qigang | Daniel |
  PolyU | qigang.zhang@connect.polyu.hk
baseurl: "" # the subpath of your site, e.g. /blog
header_pages:
  - index.md
  - research.md
  - internship.md
  - activities.md
